apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ns-apps
  namespace: openshift-gitops
spec:
  generators:
  #Despliega la app del tag en todos los secretos de los clusters que tienen esa etiqueta
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/bgd: 'bgd' 
      values: 
        app: 'bgd' 
  # - clusters:
  #     selector:
  #       matchLabels:
  #         argocd.argoproj.io/bgdk: 'bgdk'           
  #   values: 
  #     app: 'bgdk'
  template:
    metadata:
      name: '{{name}}-{{values.app}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/danifernandezs/ns-apps.git
        targetRevision: matrix-generator
        path: apps/bgd/overlays/{{values.app}}
      destination:
        server: '{{server}}'